language: generic 
sudo: required
services:
    - docker


before_install:
    - docker build -t bjornarnielsen/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bjornarnielsen/docker-react npm run test